### ISSUE TITLE
"Discover Store" Is an unexplained thing in the FAQ (Moved from FFXIVQuickLauncher #1156)

### ISSUE THREAD

**Issue by Routhinator** [goatcorp/faq#73]
I went to the FAQ and dug through issues, and cannot find any explanation of what a "Discover Store" is. I cannot find a direct link to the Linux Binary either as all the FAQs just say 'search the discover store'.

From what I can tell "Discover Store" is a KDE thing. As a Linux User running a Ubuntu Gnome desktop - I do not want to pollute my ecosystem with KDE libs. 

The FAQ needs to cover that this is a KDE/SteamOS only thing and provide a link to directly download the binary for other flavours of Linux.

As mentioned in [#1156 in FFXIVQuickLauncher](https://github.com/goatcorp/FFXIVQuickLauncher/issues/1156), I've moved this here for tracking.

**Comment by xSke** [comment]
I ran into this as well. It's not clear that there's a Flatpak variant (or that "discover store" means "flatpak"), so I was having a hard time figuring out how to install it on a non-Deck setup. Just a link to the flathub page would be appreciated for future newcomers.
