### ISSUE TITLE
How do I import *.fea hotbar/settings backups from the official client?

### ISSUE THREAD

**Issue by Routhinator** [goatcorp/faq#74]
As the title says, how do I import *.fea hotbar/settings backups from the official client? I seem to be struggling to find any mention of this in the FAQ.

**Comment by reiichi001** [comment]
Hello! You'll need to use the official launcher for that. XIVLauncher doesn't do any special processing for that file. 

If you're trying to move settings across devices, I'd recommend using the Lobby Server's upload/download feature, which can be found in the gear icon for each character on the Character Select screen instead. (And then SE also has to hold a backup of them too)

**Comment by Routhinator** [comment]
Cool, maybe this could go into the FAQ? Seems like something enough users may ask.

**Comment by reiichi001** [comment]
You are possibly the first person to ask. It's not a frequently asked question. 

We do have a FAQ entry for migration FFXIV installs and settings though, https://goatcorp.github.io/faq/xl_troubleshooting#q-how-do-i-migrate-ffxiv-andor-xivlauncher-files-from-an-old-installation-to-a-new-one-windows
